spotify_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: "{{ env_var('SPOTIFY_DB_USER') }}"
      password: "{{ env_var('SPOTIFY_DB_PASS') }}"
      port: 5432
      dbname: "{{ env_var('SPOTIFY_DB') }}"
      schema: analytics
      threads: 1